export const SET_CATE_LIST="SET_CATE_LIST"
export const SET_GOODS_LIST="SET_GOODS_LIST"
export const SET_GOODS_GROUP_LIST="SET_GOODS_GROUP_LIST"
export const CHECK_GOODS="CHECK_GOODS"
export const CHECK_ALL_GOODS="CHECK_ALL_GOODS"
export const CHNAGE_GOODS_NUM="CHNAGE_GOODS_NUM"
export const ADD_CART="ADD_CART"
export const SET_SEARCH_LIST="SET_SEARCH_LIST"
export const SET_GOODS_DETAIL_LIST="SET_GOODS_DETAIL_LIST"
export const SET_GOODS_DETAIL_ITEM="SET_GOODS_DETAIL_ITEM"
export const SET_KEYWORDS="SET_KEYWORDS"
export const SET_OLD_SEARCH_LIST="SET_OLD_SEARCH_LIST"
export const SET_LOADING="SET_LOADING"
export const SET_TABS_OFFSET_TOP="SET_TABS_OFFSET_TOP"
export const SET_SEARCH_DETAIL_ITEM="SET_SEARCH_DETAIL_ITEM"





